# --- USER SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/firebase-key.json
          volumeMounts:
            - name: firebase-key-vol
              mountPath: /app/firebase-key.json
              subPath: firebase-key.json
      volumes:
        - name: firebase-key-vol
          secret:
            secretName: firebase-key
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 80         # Gateway will call http://user-service (defaults to port 80)
      targetPort: 8080 # This maps to the containerPort above
---
# --- GATEWAY SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort # Allows your browser to talk to the gateway
  selector:
    app: gateway-service
  ports:
    - port: 8080
      targetPort: 8080